# Generated by Django 3.0.5 on 2020-06-06 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='user',
            new_name='created_by',
        ),
    ]
