# Generated by Django 3.0.5 on 2020-06-04 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='user',
        ),
    ]
