# Generated by Django 3.0.5 on 2020-06-26 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('woop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='criteria',
            field=models.TextField(blank=True, null=True, verbose_name='成功基準'),
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('step_id', models.AutoField(primary_key=True, serialize=False)),
                ('step_title', models.CharField(max_length=255, verbose_name='ステップ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_by', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step', to='woop.Goal')),
            ],
        ),
    ]
