# Generated by Django 3.0.5 on 2020-07-02 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('woop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['order_by']},
        ),
        migrations.AddField(
            model_name='task',
            name='criteria',
            field=models.TextField(blank=True, null=True, verbose_name='成功基準'),
        ),
        migrations.AddField(
            model_name='task',
            name='goal_description',
            field=models.TextField(blank=True, null=True, verbose_name='詳細'),
        ),
        migrations.AlterField(
            model_name='step',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='woop.Goal'),
        ),
    ]
