# Generated by Django 3.0.5 on 2020-06-26 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('woop', '0002_auto_20200626_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='woop.Step'),
        ),
        migrations.AlterField(
            model_name='task',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='woop.Board'),
        ),
    ]
