# Generated by Django 3.0.5 on 2020-06-06 08:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('woop', '0002_auto_20200606_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='gift_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
