# Generated by Django 3.0.5 on 2020-07-02 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woop', '0002_auto_20200702_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='goal_description',
            new_name='task_description',
        ),
    ]
