# Generated by Django 3.0.5 on 2020-06-04 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('woop', '0002_auto_20200604_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='backup_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='woop.Task'),
        ),
    ]
