# Generated by Django 3.0.5 on 2020-07-02 12:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('woop', '0003_auto_20200702_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expectation',
            fields=[
                ('expectation_id', models.AutoField(primary_key=True, serialize=False)),
                ('tbd_satisfaction', models.IntegerField(choices=[(20, 20), (40, 40), (60, 60), (80, 80), (100, 100)], null=True, verbose_name='予想の満足度')),
                ('tbd_satis_comment', models.CharField(max_length=200, verbose_name='満足度の予想について一言')),
                ('satisfaction', models.IntegerField(choices=[(20, 20), (40, 40), (60, 60), (80, 80), (100, 100)], null=True, verbose_name='実際の満足度')),
                ('satis_comment', models.CharField(max_length=200, verbose_name='実際の満足度について一言')),
                ('tbd_difficulty', models.IntegerField(choices=[(20, 20), (40, 40), (60, 60), (80, 80), (100, 100)], null=True, verbose_name='予想の困難度')),
                ('tbd_diff_comment', models.CharField(max_length=200, verbose_name='満足度の予想について一言')),
                ('difficulty', models.IntegerField(choices=[(20, 20), (40, 40), (60, 60), (80, 80), (100, 100)], null=True, verbose_name='実際の困難度')),
                ('diff_comment', models.CharField(max_length=200, verbose_name='実際の困難度について一言')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expectations', to='woop.Task')),
            ],
        ),
    ]
