# Generated by Django 3.0.5 on 2020-06-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woop', '0003_auto_20200606_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='first_hint',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ヒント1'),
        ),
        migrations.AddField(
            model_name='note',
            name='second_hint',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ヒント2'),
        ),
        migrations.AddField(
            model_name='note',
            name='third_hint',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ヒント3'),
        ),
    ]
