# Generated by Django 3.0.5 on 2020-06-23 07:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('woop', '0004_auto_20200614_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hurdle',
            fields=[
                ('hurdle_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hurdle', models.TextField(blank=True, null=True, verbose_name='障害')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hurdles', to='woop.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('solution_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('solution', models.TextField(blank=True, null=True, verbose_name='解決策')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('hurdle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='woop.Hurdle')),
            ],
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('reason_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, null=True, verbose_name='理由')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='woop.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='報酬')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='woop.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_name', models.TextField(blank=True, null=True, verbose_name='資料')),
                ('document_use', models.CharField(blank=True, max_length=200, null=True, verbose_name='用途')),
                ('document_source', models.URLField(blank=True, null=True, verbose_name='場所')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='woop.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Discover',
            fields=[
                ('discover_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discover_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='タイトル')),
                ('discover_main', models.TextField(blank=True, null=True, verbose_name='本文')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日時')),
                ('first_hint', models.CharField(blank=True, max_length=20, null=True, verbose_name='ヒント1')),
                ('second_hint', models.CharField(blank=True, max_length=20, null=True, verbose_name='ヒント2')),
                ('third_hint', models.CharField(blank=True, max_length=20, null=True, verbose_name='ヒント3')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovers', to='woop.Task')),
            ],
        ),
    ]
