# Generated by Django 3.0.5 on 2020-07-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woop', '0004_expectation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectation',
            name='diff_comment',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='実際の困難度について一言'),
        ),
        migrations.AlterField(
            model_name='expectation',
            name='difficulty',
            field=models.IntegerField(blank=True, choices=[(20, 20), (40, 40), (60, 60), (80, 80), (100, 100)], null=True, verbose_name='実際の困難度'),
        ),
        migrations.AlterField(
            model_name='expectation',
            name='satis_comment',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='実際の満足度について一言'),
        ),
        migrations.AlterField(
            model_name='expectation',
            name='satisfaction',
            field=models.IntegerField(blank=True, choices=[(20, 20), (40, 40), (60, 60), (80, 80), (100, 100)], null=True, verbose_name='実際の満足度'),
        ),
        migrations.AlterField(
            model_name='expectation',
            name='tbd_diff_comment',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='満足度の予想について一言'),
        ),
        migrations.AlterField(
            model_name='expectation',
            name='tbd_difficulty',
            field=models.IntegerField(blank=True, choices=[(20, 20), (40, 40), (60, 60), (80, 80), (100, 100)], null=True, verbose_name='予想の困難度'),
        ),
        migrations.AlterField(
            model_name='expectation',
            name='tbd_satis_comment',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='満足度の予想について一言'),
        ),
        migrations.AlterField(
            model_name='expectation',
            name='tbd_satisfaction',
            field=models.IntegerField(blank=True, choices=[(20, 20), (40, 40), (60, 60), (80, 80), (100, 100)], null=True, verbose_name='予想の満足度'),
        ),
    ]
