# Generated by Django 3.0.5 on 2020-06-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woop', '0005_discover_document_feedback_hurdle_reason_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='difficulty',
            field=models.IntegerField(blank=True, choices=[(10, 'かなり簡単'), (20, '簡単'), (30, '普通'), (40, '難しい'), (50, 'かなり難しい')], null=True, verbose_name='困難度'),
        ),
        migrations.AddField(
            model_name='task',
            name='satisfaction',
            field=models.IntegerField(blank=True, choices=[(10, '全くない'), (20, 'あまりない'), (30, 'ほどほど'), (40, 'ある'), (50, 'かなりある')], null=True, verbose_name='満足度'),
        ),
    ]
