# Generated by Django 3.0.5 on 2020-04-19 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('woop', '0005_auto_20200419_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='woop.Goal'),
        ),
    ]
