# Generated by Django 3.0.5 on 2020-06-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woop', '0006_auto_20200624_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='difficulty',
            field=models.IntegerField(choices=[(10, 'かなり簡単'), (20, '簡単'), (30, '普通'), (40, '難しい'), (50, 'かなり難しい')], null=True, verbose_name='困難度'),
        ),
        migrations.AlterField(
            model_name='task',
            name='satisfaction',
            field=models.IntegerField(choices=[(10, '全くない'), (20, 'あまりない'), (30, 'ほどほど'), (40, 'ある'), (50, 'かなりある')], null=True, verbose_name='満足度'),
        ),
    ]
