# Generated by Django 3.0.5 on 2020-04-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woop', '0007_auto_20200421_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_title',
            field=models.CharField(max_length=200, verbose_name='目標'),
        ),
    ]
