# Generated by Django 3.0.5 on 2020-04-25 20:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('woop', '0008_auto_20200426_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='achievement',
            field=models.IntegerField(blank=True, null=True, verbose_name='達成度'),
        ),
        migrations.AddField(
            model_name='goal',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='締め切り'),
        ),
        migrations.AddField(
            model_name='goal',
            name='goal_description',
            field=models.TextField(blank=True, null=True, verbose_name='詳細'),
        ),
        migrations.AddField(
            model_name='goal',
            name='progress_type',
            field=models.IntegerField(blank=True, choices=[(0, '一時停止'), (1, '挑戦中'), (2, '達成済')], null=True, verbose_name='進捗状況'),
        ),
        migrations.AddField(
            model_name='goal',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='開始日'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時'),
        ),
    ]
