# Generated by Django 3.0.5 on 2020-04-25 22:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('woop', '0010_motive'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfTranscendenceGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('self_transcendence_goal', models.TextField(blank=True, null=True, verbose_name='自己超越目標')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_transcendence_goals', to='woop.Goal')),
            ],
        ),
    ]
