# Generated by Django 3.0.5 on 2020-04-25 23:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('woop', '0011_selftranscendencegoal'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureSelf',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('future_self', models.TextField(blank=True, null=True, verbose_name='将来の自分')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='future_selves', to='woop.Goal')),
            ],
        ),
    ]
