# Generated by Django 3.0.5 on 2020-04-26 00:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('woop', '0013_worry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idea', models.TextField(blank=True, null=True, verbose_name='対策')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('worry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='woop.Worry')),
            ],
        ),
    ]
