# Generated by Django 3.0.5 on 2020-04-28 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woop', '0014_idea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='futureself',
            old_name='id',
            new_name='future_id',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='id',
            new_name='goal_id',
        ),
        migrations.RenameField(
            model_name='idea',
            old_name='id',
            new_name='idea_id',
        ),
        migrations.RenameField(
            model_name='motive',
            old_name='id',
            new_name='motive_id',
        ),
        migrations.RenameField(
            model_name='selftranscendencegoal',
            old_name='id',
            new_name='selftrans_id',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='id',
            new_name='task_id',
        ),
        migrations.RenameField(
            model_name='worry',
            old_name='id',
            new_name='worry_id',
        ),
    ]
